# name: Build and deploy Python app to Azure Web App - studentperfomance

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python version
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.10'

#       - name: Cache pip dependencies
#         uses: actions/cache@v3
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       - name: Create and start virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate
      
#       - name: Install dependencies
#         run: |
#           source venv/bin/activate
#           pip install -r requirements.txt

#       # Optional: Run tests
#       # - name: Run tests
#       #   run: |
#       #     source venv/bin/activate
#       #     pytest

#       - name: Upload artifact for deployment jobs
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-app
#           path: |
#             .
#             !venv/
#             !.git/
#             !.github/
#             !__pycache__/

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       id-token: write
#       contents: read

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: python-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B4F62A8E06C24611A59AF43C75C8D338 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93E63403D4814D7B89D13C5F7EB0CCED }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A290F7ECF08D4429996EFFEB006B4258 }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'studentperfomance'
#           slot-name: 'Production'

